#!/bin/bash

url=$1
if [ ! -d "$url" ]; then
    mkdir -p "$url/recon/final"
fi

echo "[+] Enumerating subdomains with Subfinder... "
docker run --rm projectdiscovery/subfinder:latest -d "$url" > "$url/recon/subfinder.txt"
cat "$url/recon/subfinder.txt" >> "$url/recon/final/final.txt"

echo "[+] Enumerating subdomains with Amass... "
timeout 120s amass enum -d "$url" > "$url/recon/amass.txt"
cat "$url/recon/amass.txt" >> "$url/recon/final/final.txt"

echo "[+] Enumerating subdomains with assetfinder... "
assetfinder --subs-only "$url" > "$url/recon/assetfinder.txt"
cat "$url/recon/assetfinder.txt" >> "$url/recon/final/final.txt"

echo "[+] Removing duplicates... "
sort -u "$url/recon/final/final.txt" > "$url/recon/final/sorted_final.txt"

echo "[+] Probing live domains... "
cat "$url/recon/final/sorted_final.txt" | httprobe > "$url/recon/final/live.txt"

echo "[+] Taking screenshots... "
gowitness scan file -f "$url/recon/final/live.txt" --screenshot-fullpage --screenshot-path "$url/recon/final/screenshots

echo "[+] Recon complete!"
